# Generated by Django 5.1.5 on 2025-01-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$2b070VE0mbQ6Iokl8yV6Or$WUDrOP6/+acJ6oEj6nw/z5v7blBJ/kYmxcBETsq7VuE=', max_length=128, verbose_name='password'),
        ),
    ]
