# Generated by Django 5.1.5 on 2025-01-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$8YO6Ixj5dog7lXmnXVULuX$UDY5l38GNxHY2vGt8MlOPMXvVX8Ow2dsWeUarMpbxbI=', max_length=128, verbose_name='password'),
        ),
    ]
