# Generated by Django 5.1.5 on 2025-01-29 23:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$chvktShF9dzlq1wRG3qmUX$41JrbbyHV6zgd6HPlw7cD+QOHl6DLDuYDZkaJDxoKwk=', max_length=128, verbose_name='password'),
        ),
    ]
