# Generated by Django 5.1.5 on 2025-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_email_verification_token_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$sqZ1qD9iRHnA0Y2lVOYpPd$6t1yY2v9YeZqFI+cYJdwgTWFMpzcqq4AbJfITJ0fFmE=', max_length=128, verbose_name='password'),
        ),
    ]
