# Generated by Django 5.1.5 on 2025-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$qQtQTHQYTH01t48VoUJZzM$pEPX+IJ623KBhlGR2fL8++icXIrpL8Pmssjd1Gejcjk=', max_length=128, verbose_name='password'),
        ),
    ]
