# Generated by Django 5.1.5 on 2025-01-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$SFm8JRCjeuWnH91ccQXZwH$RKMTnJrnIT9uscVihWNCpCpxP++TUsaBTo7077abJPI=', max_length=128, verbose_name='password'),
        ),
    ]
