# Generated by Django 5.1.5 on 2025-01-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$HdLwNvb2aPc9hnpIZl7vTU$2CBRW+id0mLAEPW1g8mv6eb5Rt9kQMgR1Ss+AwEf/kI=', max_length=128, verbose_name='password'),
        ),
    ]
