# Generated by Django 5.1.5 on 2025-01-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(max_length=82, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$eTAgjFiMkob6jOU2FbOHKw$LCbKhHHKB+sK470SQag1GIsArjS9/ID8crYuAAZZvSA=', max_length=128, verbose_name='password'),
        ),
    ]
