# Generated by Django 5.1.5 on 2025-01-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$iGp2BxKUKfeMIsHVJpr2Q4$ngpQXlmlZjopmirIpDGk1p+W3V6qp4ULcNZH+Do1eKQ=', max_length=128, verbose_name='password'),
        ),
    ]
