# Generated by Django 5.1.5 on 2025-01-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$BZT8UaftJUH0DdodnndRcg$hlyifvUeYMJdLoJdqcVz5+3SaG02NiqijTuDGLg/Tro=', max_length=128, verbose_name='password'),
        ),
    ]
