# Generated by Django 5.1.5 on 2025-01-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_reset_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$9Mg4PiRhOacPtpXOk06jgI$x6XBEQ7sPczU7Cn1lPlZcQn6Hbw4ey3IbSOLNNj4Hr0=', max_length=128, verbose_name='password'),
        ),
    ]
