# Generated by Django 5.1.5 on 2025-01-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_user_password_reset_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$yOTzWYKDPDD9hv5UCMhAWg$xESWH94J5iNf91YVg6ufZ43PzI/mijm7Emgza2oWkLM=', max_length=128, verbose_name='password'),
        ),
    ]
