# Generated by Django 5.1.5 on 2025-01-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$1qtsvXDEpunZTTvmDqFDsw$va0jJeE8fqlDSdnEuOLPxsHEn17SIcNW7mqu9goQ9FM=', max_length=128, verbose_name='password'),
        ),
    ]
