# Generated by Django 5.1.5 on 2025-01-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$5nSCLc2RIgpUr46GPDmkow$h6WLuMSI1d7WtBjbynoD9yE83l3pd3d5d7Y2zLddl5w=', max_length=128, verbose_name='password'),
        ),
    ]
