# Generated by Django 5.1.5 on 2025-01-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$r3BUtDXKIiQhzaSXRMES9A$pT5GfUqJUgVMLyfeToEsJBLm59nU4th4BSMezyWupbw=', max_length=128, verbose_name='password'),
        ),
    ]
