# Generated by Django 5.1.5 on 2025-02-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$iJAV5aUbgCHC4pBb3xVfUI$lkCQALPqdoKd21HwLiIMOF1adCTKquFQgU++UdjTbME=', max_length=128, verbose_name='password'),
        ),
    ]
