# Generated by Django 5.1.5 on 2025-02-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$sHO8lc8h0A1CMQhcmaEXmV$CjtwzxiX4449JcqyvqrJNGa4bL9w9Q752WgKySpMTUw=', max_length=128, verbose_name='password'),
        ),
    ]
