# Generated by Django 5.1.5 on 2025-02-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$lRTzRhotBlIgOqFduA6cR5$VHyHPiwu7p0YE+Rj2xaBA1UP16CUn4S8nMzpMqOhwC0=', max_length=128, verbose_name='password'),
        ),
    ]
