# Generated by Django 5.1.5 on 2025-02-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$WUuquGe4EwBVZswwmvpIr7$a7mV8pSIsx7Lzm3Q3qwdCIBlrHVSnSe0VaHtiNjTEEc=', max_length=128, verbose_name='password'),
        ),
    ]
