# Generated by Django 5.1.5 on 2025-03-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$xpor33weroKT7zrBKKYe6l$mhU6WBoF/bE9D4NkaP8KOtC8l6uoHGau4VeP2ipYxQg=', max_length=128, verbose_name='password'),
        ),
    ]
