# Generated by Django 5.1.5 on 2025-03-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$AZfhPJ0TnF4hkWIGjpJKKG$JeaQKl9TgCGKkRq+BPok+CnsI2lj+AvhQdlTb/IPH9M=', max_length=128, verbose_name='password'),
        ),
    ]
