# Generated by Django 5.1.7 on 2025-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$0G9i3irkkIe525vVw6c0oD$0RGMOSieMvq+o7uzJFTq4ACdX3Q7ile4K60FDGVQ0OA=', max_length=128, verbose_name='password'),
        ),
    ]
