# Generated by Django 5.1.7 on 2025-03-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$2cKZwxRZBWi6GLCbpOxO01$8gHC7LAcwmL9XOW6N2O8NuELxT5g7usXdQuSq81A3Ao=', max_length=128, verbose_name='password'),
        ),
    ]
