# Generated by Django 5.1.7 on 2025-03-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$9hogOxT5iPFhkEKVz1mjc4$za4riiRFbffxC7N945hvm29A5pgbggzAkZlvCDEgIrw=', max_length=128, verbose_name='password'),
        ),
    ]
