# Generated by Django 5.1.7 on 2025-03-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$vG7Pfq5MeAYUo7ViMskUs7$IauvMBfZ19q46IrAqIp8cJTRC/mAGSLv+XsaIXEMnu0=', max_length=128, verbose_name='password'),
        ),
    ]
