# Generated by Django 5.1.7 on 2025-03-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$v8HBVLptp3jWdP8Sng5BGW$MtrPU+WgDreUFDPHzcBvb0p1NZHY2nNQX29VrJD/yoc=', max_length=128, verbose_name='password'),
        ),
    ]
