# Generated by Django 5.1.7 on 2025-03-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$LYxaiK9WP1tprvxkBP4hal$XJ++RDNXVqaBUTbkEswRXj0EYG+39gModx0qViZWBfc=', max_length=128, verbose_name='password'),
        ),
    ]
