# Generated by Django 5.1.7 on 2025-03-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$07mhIBnhgSk0V3zZuVPfGD$sEnP2kasjEZ8YHk7+6fhEKEbn1BfNyrxKQFLxHW4SBc=', max_length=128, verbose_name='password'),
        ),
    ]
