# Generated by Django 5.1.7 on 2025-04-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$pjwLAKQYATd3o2z3b36q89$zfO8mCjW/oKiqfTsJWDtj+WuHS5oFDvCh7OQUjgVbW8=', max_length=128, verbose_name='password'),
        ),
    ]
