# Generated by Django 5.1.7 on 2025-04-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$QxnrFfC486yOgq4BfpD85y$sfAquBhmTfDqiiQsglDJklUYPiZvXcvMcqS3dkvIcms=', max_length=128, verbose_name='password'),
        ),
    ]
