# Generated by Django 5.1.7 on 2025-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$DDBNxEIDrYwCpa0rNoCSMv$SPVG2l8OUKot0vKoJLOMWyMV9AWp8VmDQog1vIJ/RZo=', max_length=128, verbose_name='password'),
        ),
    ]
