# Generated by Django 5.1.7 on 2025-04-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$pQ66djxSZQUaBgGM432F68$W+0O06peqLxOpfTAsSbc1ezPA9JWpMf/LJ7OtMqrlW4=', max_length=128, verbose_name='password'),
        ),
    ]
