# Generated by Django 5.1.7 on 2025-04-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$9y9DfAHW4B61haIcsoe1Ee$rpP9jGS0KFqxR7x7Zg8FF7TcWHtBwopqCewgZWmSPdY=', max_length=128, verbose_name='password'),
        ),
    ]
