# Generated by Django 5.1.7 on 2025-04-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$NP7HwPlCF8Wx0Z3U6M0hjc$CvN+B12FAxP4M0+zIWXWhlHcj+8PKGlAzOXk1muEt7U=', max_length=128, verbose_name='password'),
        ),
    ]
