# Generated by Django 5.1.7 on 2025-04-13 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$0HWS1uUMJJ2jg6oaCHSRFq$VB0UVgEi64Kz0UhnTcI4hbFRINKbw+K3TGylot5Xo0M=', max_length=128, verbose_name='password'),
        ),
    ]
