# Generated by Django 5.1.7 on 2025-04-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$EDl4qwC6Kcc1BXGuSTiLVN$8UgKtGIgeNVPjAm8WW2z0YUpvfK0/z0WxlJzBRr20ms=', max_length=128, verbose_name='password'),
        ),
    ]
