# Generated by Django 5.1.7 on 2025-04-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$2txyfUykTraoclSx9Cu7Y6$zJMeRgqBlu0I9d/rxfjYwEu0R+K4/KEWcDumCgal0bI=', max_length=128, verbose_name='password'),
        ),
    ]
