# Generated by Django 5.1.7 on 2025-04-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$ChpFp4MMtS1NHdYRlsyTJF$bAYCxJvl33L5sIIvZgWjtfw+EM482j5cmwnyYA281go=', max_length=128, verbose_name='password'),
        ),
    ]
