# Generated by Django 5.1.7 on 2025-04-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$rf3HP9sre1EoQbwtiUSpcC$5Yn6qU42XQW5vLz5mQJb00v8LUWgghsXE7Y8PyrfHGw=', max_length=128, verbose_name='password'),
        ),
    ]
