# Generated by Django 5.1.7 on 2025-04-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$swhylYsCKqchm2vBuvumIU$gpRMq/pucuBkl5tkzO84KHSIMZcdTGKt3jyMgR95Jsk=', max_length=128, verbose_name='password'),
        ),
    ]
