# Generated by Django 5.1.7 on 2025-04-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('drive_preparing', 'Driver Preparing Delivery'), ('driver_en_route', 'Driver En Route'), ('driver_complete', 'Delivery Complete'), ('driver_misdelivery', 'Misdelivery'), ('driver_rescheduled', 'Rescheduled'), ('driver_canceled', 'Canceled')], max_length=50)),
                ('content', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'event')},
            },
        ),
    ]
