# Generated by Django 5.1.7 on 2025-04-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetemplate',
            name='event',
            field=models.CharField(choices=[('driver_preparing', 'Driver Preparing Delivery'), ('driver_en_route', 'Driver En Route'), ('driver_complete', 'Delivery Complete'), ('driver_misdelivery', 'Misdelivery'), ('driver_rescheduled', 'Rescheduled'), ('driver_canceled', 'Canceled')], max_length=50),
        ),
    ]
