# Generated by Django 5.1.5 on 2025-02-05 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderitem_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('accepted_by_driver', 'Accepted by Driver(s)'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('misdelivery', 'Misdelivery'), ('redelivery_assigned', 'Redelivery Assigned'), ('redelivery_in_progress', 'Redelivery In Progress'), ('redelivery_complete', 'Redelivery Complete'), ('canceled', 'Canceled')], default='order_placed', max_length=30)),
                ('assigned_delivery_date', models.DateField()),
                ('assigned_delivery_time', models.TimeField()),
                ('previous_assignments', models.JSONField(default=list)),
                ('drivers', models.ManyToManyField(related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orders.order')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
            },
        ),
    ]
