# Generated by Django 5.1.7 on 2025-03-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('accepted_by_driver', 'Accepted by Driver(s)'), ('en_route', 'En Route'), ('complete', 'Complete'), ('misdelivery', 'Misdelivery'), ('redelivery_assigned', 'Redelivery Assigned'), ('redelivery_in_progress', 'Redelivery In Progress'), ('redelivery_complete', 'Redelivery Complete'), ('canceled', 'Canceled')], default='order_placed', max_length=30),
        ),
    ]
