# Generated by Django 5.1.7 on 2025-04-11 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_status'),
        ('orders', '0005_order_delivery_date_order_hasimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('accepted_by_driver', 'Accepted by Driver(s)'), ('en_route', 'En Route'), ('complete', 'Complete'), ('misdelivery', 'Misdelivery'), ('canceled', 'Canceled')], max_length=30)),
                ('delivery_date', models.DateField()),
                ('delivery_time', models.TimeField()),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drivers', models.ManyToManyField(related_name='delivery_attempts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='AttemptedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_attempted', models.PositiveIntegerField(default=1)),
                ('issue', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='orders.orderitem')),
                ('delivery_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_items', to='assignments.deliveryattempt')),
            ],
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
