# Generated by Django 5.1.7 on 2025-04-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_deliveryattempt_attempteditem_delete_assignment'),
        ('orders', '0005_order_delivery_date_order_hasimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('delivery_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_items', to='assignments.deliveryattempt')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_attempts', to='orders.orderitem')),
            ],
        ),
        migrations.DeleteModel(
            name='AttemptedItem',
        ),
    ]
