# Generated by Django 5.1.7 on 2025-04-12 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_scheduleditem_delete_attempteditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattempt',
            name='miles_to_arrival',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='mins_to_arrival',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='drivers',
            field=models.ManyToManyField(related_name='drivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('accepted_by_driver', 'Accepted by Driver(s)'), ('en_route', 'En Route'), ('complete', 'Complete'), ('misdelivery', 'Misdelivery'), ('rescheduled', 'Rescheduled'), ('canceled', 'Canceled')], max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='delivery_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='assignments.deliveryattempt')),
            ],
        ),
    ]
