# Generated by Django 5.1.7 on 2025-04-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_deliveryattempt_miles_to_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattempt',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
