# Generated by Django 5.1.7 on 2025-04-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_deliveryattempt_status_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattempt',
            name='completion_sms_sent',
            field=models.BooleanField(default=False),
        ),
    ]
