# Generated by Django 5.1.7 on 2025-04-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_deliveryattempt_completion_sms_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryattempt',
            name='status',
            field=models.CharField(choices=[('order_placed', 'Order Placed'), ('assigned_to_driver', 'Assigned to Driver(s)'), ('accepted_by_driver', 'Accepted by Driver(s)'), ('en_route', 'En Route'), ('complete', 'Complete'), ('misdelivery', 'Misdelivery'), ('rescheduled', 'Rescheduled'), ('canceled', 'Canceled')], max_length=30),
        ),
    ]
