# Generated by Django 5.1.7 on 2025-04-19 19:52

import assignments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0008_alter_deliveryattempt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryphoto',
            name='signed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryphoto',
            name='signed_url_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryphoto',
            name='image',
            field=models.ImageField(upload_to=assignments.models.delivery_photo_upload_path),
        ),
    ]
