# Generated by Django 5.1.7 on 2025-05-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_deliveryphoto_signed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattempt',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
