# Generated by Django 5.1.7 on 2025-05-17 01:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0010_deliveryattempt_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryattempt',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='drivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
