# Generated by Django 5.1.7 on 2025-04-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_delivery_date_order_hasimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hasImage',
        ),
    ]
