# Generated by Django 5.1.7 on 2025-05-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_hasimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='preferred_delivery_time',
        ),
    ]
