# Generated by Django 5.1.7 on 2025-05-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_preferred_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_instructions',
        ),
    ]
