# Generated by Django 5.1.7 on 2025-05-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date_fallback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_fallback',
            field=models.CharField(blank=True, default='order_placed', max_length=30, null=True),
        ),
    ]
