# Generated by Django 5.1.7 on 2025-05-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivery_date_fallback_order_status_fallback'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_pd',
            field=models.FileField(blank=True, help_text='PDF Invoice File', null=True, upload_to='invoices/'),
        ),
    ]
