# Generated by Django 5.1.7 on 2025-05-20 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_invoice_pd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='invoice_pd',
            new_name='invoice_pdf',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_pdf_signed_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_pdf_signed_url_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
