from django.urls import path, include

from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from .accounts.views import UserViewSet
from .stores.views import StoreViewSet
from api.products.views import ProductListCreate, ProductImportView, SearchProductView
from api.orders.views import OrderViewSet
from api.assignments.views import AssignmentViewSet

from .views import LogoutView

from django.conf import settings
from django.conf.urls.static import static


# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'stores', StoreViewSet)
router.register(r'orders', OrderViewSet, basename='orders')
router.register(r'assignments', AssignmentViewSet)

# API URL configuration
urlpatterns = [
    path('', include(router.urls)),
    path('login/', TokenObtainPairView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
    path('logout/', LogoutView.as_view()),
    # DELETE LATER
    path('products/', ProductListCreate.as_view(), name='product-list-create'),
    path('import-products/', ProductImportView.as_view(), name="import-products"),
    path('search-product/', SearchProductView.as_view(), name="search-product"),
    path('api/users/me/', UserViewSet.as_view({'get':'me'})),
    path('api/users/me/stores', UserViewSet.as_view({'get':'my_stores'})),
    ]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""
API URLs generated by router:
  <URLPattern '^users/$' [name='user-list']>
  <URLPattern '^users\.(?P<format>[a-z0-9]+)/?$' [name='user-list']>
  <URLPattern '^users/verify_email/$' [name='user-verify-email']>
  <URLPattern '^users/verify_email\.(?P<format>[a-z0-9]+)/?$' [name='user-verify-email']>
  <URLPattern '^users/(?P<pk>[^/.]+)/$' [name='user-detail']>
  <URLPattern '^users/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='user-detail']>
  <URLPattern '^users/(?P<pk>[^/.]+)/stores/$' [name='user-stores']>
  <URLPattern '^users/(?P<pk>[^/.]+)/stores\.(?P<format>[a-z0-9]+)/?$' [name='user-stores']>
  <URLPattern '^stores/$' [name='store-list']>
  <URLPattern '^stores\.(?P<format>[a-z0-9]+)/?$' [name='store-list']>
  <URLPattern '^stores/(?P<pk>[^/.]+)/$' [name='store-detail']>
  <URLPattern '^stores/(?P<pk>[^/.]+)\.(?P<format>[a-z0-9]+)/?$' [name='store-detail']>
  <URLPattern '^stores/(?P<pk>[^/.]+)/users/$' [name='store-users']>
  <URLPattern '^stores/(?P<pk>[^/.]+)/users\.(?P<format>[a-z0-9]+)/?$' [name='store-users']>
  <URLPattern '' [name='api-root']>
  <URLPattern '<drf_format_suffix:format>' [name='api-root']>
System check identified no issues (0 silenced).
"""

"""
GET    /api/users/           - List users
POST   /api/users/           - Create user
GET    /api/users/{id}/      - Get specific user
PUT    /api/users/{id}/      - Update user
DELETE /api/users/{id}/      - Delete user

GET    /api/stores/          - List stores
POST   /api/stores/          - Create store
GET    /api/stores/{id}/     - Get specific store
PUT    /api/stores/{id}/     - Update store
DELETE /api/stores/{id}/     - Delete store
"""