# Generated by Django 5.1.5 on 2025-01-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=50)),
                ('google_id', models.CharField(max_length=255, unique=True)),
                ('image_link', models.URLField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sell_on_google_quantity', models.PositiveIntegerField(default=0)),
                ('availability', models.CharField(max_length=50)),
                ('mpn', models.CharField(blank=True, max_length=50, null=True)),
                ('gtin', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('shipping_weight', models.CharField(blank=True, max_length=50, null=True)),
                ('google_product_category', models.CharField(blank=True, max_length=255, null=True)),
                ('product_type', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
